//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace clawSoft.clawPDF.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clawSoft.clawPDF.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] eciRGB_v2 {
            get {
                object obj = ResourceManager.GetObject("eciRGB_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ISOcoated_v2_300_eci {
            get {
                object obj = ResourceManager.GetObject("ISOcoated_v2_300_eci", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ISOcoated_v2_grey1c_bas {
            get {
                object obj = ResourceManager.GetObject("ISOcoated_v2_grey1c_bas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 %!
        ///% This is a sample prefix file for creating a PDF/A document.
        ///% Feel free to modify entries marked with &quot;Customize&quot;.
        ///
        ///% This assumes an ICC profile to reside in the file (ISO Coated sb.icc),
        ///% unless the user modifies the corresponding line below.
        ///
        ///% Define entries in the document Info dictionary :
        ///
        ////ICCProfile [ICC_PROFILE]
        ///def
        ///
        ///[ /Title (Title)                  % Customize.
        ///  /DOCINFO pdfmark
        ///
        ///% Define an ICC profile :
        ///
        ///[/_objdef {icc_PDFA} /type /stream /OBJ pdfmark
        ///[{icc_PDFA} &lt;&lt;/N  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PdfaDefinition {
            get {
                return ResourceManager.GetString("PdfaDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %!
        ///% This is a sample prefix file for creating a PDF/X-3 document.
        ///% Feel free to modify entries marked with &quot;Customize&quot;.
        ///
        ///% This assumes an ICC profile to reside in the file (ISO Coated sb.icc),
        ///% unless the user modifies the corresponding line below.
        ///
        ///systemdict /ProcessColorModel known {
        ///  systemdict /ProcessColorModel get dup /DeviceGray ne exch /DeviceCMYK ne and
        ///} {
        ///  true
        ///} ifelse
        ///{ (ERROR: ProcessColorModel must be /DeviceGray or DeviceCMYK.)=
        ///  /ProcessColorModel cvx /rangecheck signal [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PdfxDefinition {
            get {
                return ResourceManager.GetString("PdfxDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %!PS
        ////stampstring ([STAMPSTRING]) def
        ////fontname /[FONTNAME] def
        ////fontsize [FONTSIZE] def
        ////fontcolor {[FONTCOLOR]} def
        ////ISOLatin1Encoding [
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /space/exclam/quotedbl/numbersign/dollar/percent/ampersand/quoteright
        ///    /parenle [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PostScriptStamp {
            get {
                return ResourceManager.GetString("PostScriptStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] WebCoatedFOGRA28 {
            get {
                object obj = ResourceManager.GetObject("WebCoatedFOGRA28", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
